# Generated by Django 4.1.5 on 2023-01-24 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название сообщества. Максимум 100 символов.",
                        max_length=200,
                        verbose_name="Название сообщества",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Введите адрес сообщества. Допускаются английские буквы, цифры, символ подчеркивания.",
                        unique=True,
                        verbose_name="Сетевой адрес",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание сообщества.",
                        verbose_name="Описание сообщества",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщество",
                "verbose_name_plural": "Сообщества",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Введите текст публикации.",
                        verbose_name="Текст публикации",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату публикации.",
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите автора публикации",
                        on_delete=models.SET(posts.models.get_sentinel_user),
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор публикации",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите сообщество, в котором разместить публикацию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="posts.group",
                        verbose_name="Сообщество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ("-pub_date",),
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Выберите автора поста",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор поста",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Выберите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписчики",
                "verbose_name_plural": "Подписчики",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Введите комментарий к посту.",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату комментарий.",
                        verbose_name="Дата комментария",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Выберите автора комментария.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Выберите комментируемый пост.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                        verbose_name="Комментируемый пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-created",),
            },
        ),
    ]
